/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyProject;


 class LibraryTest {
 
  /*@Test void someLibraryMethodReturnsTrue() { Library classUnderTest = new
  Library(); assertTrue(classUnderTest.someLibraryMethod(),
 "someLibraryMethod should return 'true'");*/ 
	 
 } 
 